- .github/workflows/format-checks.yml
This currently only checks the C/C++ files.
> Add code format checking

- .github/workflows/format-checks.yml
- .github/workflows/sync-labels.yml
This will allow us to lock down version better if we want to.
> Switch workflows to use 3 part version

- .github/workflows/automatic-rebase.yml
- .github/workflows/sync-labels.yml
This will add a 👍 to the `/rebase` comment and add a comment on failure.
> Add automatic rebase feedback

- Libraries/WNContainers/inc/WNRangePartition.h
> Fix for Range partition

- .github/dependabot.yml
Only enable for google test for now as a test.
> Enable submodule automatic updates

- Applications/editor/main.wns
- Applications/editor/renderer/render_description.wns
- Applications/editor/renderer/rt_description.wns
- Libraries/WNScripting/inc/WNScriptHelpers.h
- Libraries/WNScripting/inc/forward.h
- Libraries/WNScripting/inc/type_manager.inl
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNSwapchain.cpp
- Overlays/Windows/Overlays/D3D12/Runtime/WNGraphics/src/D3D12/WNDevice.cpp
- Overlays/Windows/Runtime/WNWindow/inc/WNWindowsWindow.h
- Overlays/Windows/Runtime/WNWindow/src/WNWindowsWindow.cpp
- Runtime/WNGraphics/inc/WNDescriptors.h
- Runtime/WNGraphics/inc/WNFramebuffer.h
- Runtime/WNGraphics/inc/WNGraphicsPipeline.h
- Runtime/WNGraphics/inc/WNImageView.h
- Runtime/WNGraphics/inc/WNShaderModule.h
- engine/renderer/inc/render_context.h
- engine/renderer/inc/render_data.h
- engine/renderer/inc/render_pass.h
- engine/renderer/inc/render_target.h
- engine/renderer/src/render_context.cpp
- engine/renderer/src/render_pass.cpp
- engine/renderer/src/render_target.cpp
- engine/ui/inc/ui.h
- engine/ui/inc/ui_rocket_renderer.h
- engine/ui/src/ui.cpp
- engine/ui/src/ui_rocket_renderer.cpp
This also allows the UI to (mostly) resize properly. Still
a bit of work to do for this.
> Implement resizing in the engine.

- Applications/demos/rocket_test/src/main.cpp
- Libraries/WNContainers/inc/WNStringView.h
- Overlays/Posix/Libraries/WNFileSystem/src/WNSystemPaths.cpp
- Overlays/Posix/Libraries/WNFileSystem/src/WNSystemTempPath.cpp
- Overlays/Vulkan/Runtime/WNGraphics/inc/Internal/Vulkan/WNCommandList.h
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNAdapter.cpp
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNCommandList.cpp
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNDevice.cpp
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNHelpers.cpp
- Runtime/WNGraphics/inc/WNDescriptors.h
- Runtime/WNGraphics/src/WNDevice.cpp
- Runtime/WNGraphics/test/inc/WNPixelTestFixture.h
- Runtime/WNWindow/src/WNWindowFactory.cpp
- Runtime/networking/inc/routed_connection.h
Mainly around removing `return core::move`.
> Fixes for linux build

- Libraries/WNCore/inc/types.h
Removed by accident. Broke builds 😢.
> Re-add nullptr_t definition

- README.md
Note that Ninja is the only officially supported generator on Windows.
> Document clarifications

- .gitmodules
- Libraries/WNMultiTasking/inc/job_pool.h
- Libraries/WNScripting/src/WNJITEngine.cpp
- Libraries/WNScripting/src/jit_compiler.cpp
- Overlays/MultiConfig/cmake/post_add.cmake
- Overlays/MultiConfig/cmake/target_functions/post_filesystem_files.cmake
- Overlays/Windows/Overlays/D3D12/Runtime/WNGraphics/src/D3D12/WNDevice.cpp
- cmake/targets.cmake
This involves updating llvm and fixing some bugs that this
introduced.
> Update to VS2019.

- .github/workflows/automatic-rebase.yml
> Fix rebase log link

- Overlays/Posix/Libraries/WNFileSystem/CMakeLists.txt
- Overlays/Posix/Overlays/Android/Libraries/WNScripting/CMakeLists.txt
Some preemptive fixes for android.
> Android fixes

- .github/workflows/build.yml
This will hopefully help diagnose the issue with memory.
> Enable debug info for Windows docker containers

- .github/workflows/rebase.yml
Was bugging me. Don't know why 😛. Rebase is shorter than automatic rebase.
> Rename rebase workflow

- Overlays/Posix/Overlays/Clang/cmake/build_options.cmake
> Remove C++11 option

- .github/dependabot.yml
> Fix dependabot config more

- engine/engine/src/main.cpp
This will allow engine to be more versatile.
> Allow engine to open a non main.wns script.

- .gitignore
Didn't pick up changes in `librocket` and `antlr` folder properly.
> Adjust .gitignore

- README.md
> Add some more README badges

- .github/workflows/build.yml
- externals/LICENSE.tracy
This will determine if any externals have changes or any license files under externals have changed and check they are correct. This also adds the tracy license and renames llvm-project license.
> Add externals license checking

- .github/workflows/ci.yml
- .github/workflows/rebase.yml
- .github/workflows/sync-labels.yml
- .github/workflows/update-license.yml
> Clean-up workflows

- engine/ui/src/ui_rocket_renderer.cpp
This is mostly used for the GUI debugger.
> Enable temporary geometry in the renderer.

- .gitattributes
- .github/workflows/ci.yml
We can revert this once we figure out what's wrong with sccache.
> Remove sccache from Linux and Android

- Libraries/WNScripting/inc/type_manager.inl
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNAdapter.cpp
- Overlays/Vulkan/Runtime/WNGraphics/src/Vulkan/WNDevice.cpp
- applications/editor/assets/ui/header.wns
- applications/editor/assets/ui/window.rml
- engine/engine/src/main.cpp
- engine/support/src/string.cpp
- engine/ui/src/ui_scripting_event_instancer.cpp
And some code that uses these updates. This uses some of the
functionality that was added in order to give us a
clickable tab bar.
Can't actually have multiple window contents yet, but
getting there.
> A bunch more random updates to UI.

- .github/workflows/ci.yml
- .gitmodules
- Overlays/Windows/Libraries/core/inc/Internal/WNBase_MSVC.h
- Overlays/Windows/cmake/build_options.cmake
- externals/LICENSE.tracy
Update various to use `main` over `master`. Update all to latest tagged branch commit. Also fix license checker.
> Fix submodules

- .github/workflows/ci.yml
- .github/workflows/sync-labels.yml
- .github/workflows/update-license.yml
- README.md
- documents/coding-conventions/cpp.md
Fix issues with `markdownlint`. Removes these warnings. Resolves https://github.com/WNProject/WNFramework/issues/534. Will close https://github.com/WNProject/WNFramework/pull/558.
> Fix GitHub Actions issues

- Libraries/WNContainers/inc/WNHashSet.h
- Libraries/WNScripting/inc/WNEngine.h
- Libraries/WNScripting/inc/WNEngine.inl
- Libraries/WNScripting/inc/WNScriptTLS.h
- Libraries/WNScripting/lang/WNScriptAST.g
- Libraries/WNScripting/src/WNCTranslator.cpp
- Libraries/WNScripting/src/WNJITEngine.cpp
- Libraries/WNScripting/src/WNScriptASTParser.cpp
- Libraries/WNScripting/src/WNScriptASTParser.hpp
- Libraries/WNScripting/src/add_builtins.cpp
- Overlays/Posix/Libraries/WNMultiTasking/inc/internal/system_thread_yield.h
- Overlays/Posix/Libraries/WNMultiTasking/inc/internal/thread_base.h
- applications/editor/assets/ui/main.rml
- applications/editor/assets/ui/window.rml
- applications/editor/main.wns
- applications/script_test_runner/src/WNScriptTestRunner.cpp
- engine/engine/engine_scripts/ui/renderable_ui.wns
- engine/engine/src/main.cpp
- engine/engine_base/inc/context.h
- engine/engine_base/src/context.cpp
- engine/ui/inc/ui.h
- engine/ui/inc/ui_data.h
- engine/ui/inc/ui_scripting_event_instancer.h
- engine/ui/src/ui.cpp
- engine/ui/src/ui_scripting_event_instancer.cpp
- engine/ui/src/ui_static.cpp
This update provides a somewhat final update for how actors should work. There might be some updates in how the renderer interacts with actors, but for the most part this is the completed actor model.
The only thing missing is being able to defer an actor call for some amount of time.
> Another update for actors.

- .github/labeler.yml
- .github/labels.yml
> Add more labels

- .github/labeler.yml
- .github/labels.yml
- .gitignore
Just some preparation for moving docker image building into this repository.
> Add docker labels
