WNProject/WNFramework

- .github/workflows/automatic-rebase.yml
If you add a `/rebase` comment to a pull request it will be automatically rebased onto the pull requests base branch. See https://github.com/cirrus-actions/rebase for more details.
> Add ability to do automatic rebase

- .gitignore
Switched `Externals/*` to `Externals/*/*` and sorted lexicographically.  Having `Externals/*/*` will ignore all files within subfolders under `Externals` where as `Externals/*` will ignore all folders and files under `Externals`. The previous pattern caused issues with updating our `CMakeLists.txt` file under `Externals` as well as detecting sub-module updates under `Externals`.
> Adjusted .gitignore

- Libraries/WNContainers/inc/WNRangePartition.h
- engine/ui/inc/ui.h
- engine/ui/inc/ui_resources.h
- engine/ui/src/ui.cpp
This adds basic input, still missing textures, also
still missing temporary geometry. Both of those should be easy.
This "fixes" a bug with the range parition where merging nodes
was not correct. We were dropping parts of the free-list and
overwriting data, it was bad.
The "fix" is to remove the merging behavior, so now the range
partition may easily get fragmented. To be fixed (#168)
> Add input handling to ui system.

- .github/workflows/format-checks.yml
This cuts out the times used installing and configuring `clang-format`. Should also give us a more consistent way to control the `clang-format` version used.
> Switch to container for clang-format

- .github/workflows/build.yml
Removing since it is horribly slow and shouldn't be a problem since we don't do anything that is Ninja or Make specific.
> Remove "Unix Makefiles" as a build generator

- CMakeLists.txt
- Overlays/Windows/cmake/build_options.cmake
This is currently only used for MSVC. It enables `WN_MSVC_DISABLE_INCREMENTAL_LINKING` and `WN_MSVC_DISABLE_LINK_PARALLELIZATION`.
> Add WN_LOW_RESOURCE_MODE

- Overlays/Windows/cmake/build_options.cmake
- Runtime/WNGraphics/src/WNQueue.cpp
- Runtime/WNGraphics/src/WNSurface.cpp
This fixes warning about no previously undefined symbols being defined by this file.
> Fix link warning

- .github/workflows/build.yml
Only for windows cause it's a piece of crap. This will disable linker parallelization and turn off incremental linking.
> Enable low resource mode

- .github/workflows/build.yml
I noticed, when inspecting via GitHub API, that the ones that didn't work ended up having a random `\n` on the end. I'm guessing trying to do multiline yml in the name was causing issues. Linearizing the name field. This makes it longer than 80 chars but I think that's fine for the build scripts.
> Rename builds again

- .github/workflows/build.yml
This will report build details on all successful or failed runs. This will not display if the run was cancelled.
> Always report build details

- .github/workflows/build.yml
- README.md
Update documentation to state we only support **x86-64**. We can work towards removing support in code later.
> Remove x86/Win32 windows builds

- Libraries/profiling/src/profiling.cpp
We really want to avoid this but some libraries (llvm for example)
dont let us specify a custom allocator.
Eventually we want to be able to override system malloc/free
but for now at least we can get the C++ allocations.
> Add tracking of naked new/delete

- .github/workflows/build.yml
- .github/workflows/rebase.yml
This analyzes changes and determines if a code format check and/or build is needed. Helpful when making none-build related changes. Should help reduce the amount of building we have top do. This will still always run format checks and a full build on a merge to master. Resolves #253.
> Add ability to skip parts of the build

- .github/workflows/build.yml
Builds would be considered successful on build cancel.
> Always run build aggregation job

- Overlays/Windows/cmake/externals.cmake
- externals/CMakeLists.txt
The use of [get_target_property](https://cmake.org/cmake/help/v3.16/command/get_target_property.html?highlight=get_target_property) can result in the variable `COMPILE_FLAGS` being set to either `NOTFOUND` or `CFLAGS-NOTFOUND` depending on cmake version. This will hopefully catch both. Not sure why this started not working all of a sudden but this seems to have fixed it.
> Fix windows builds

- .github/workflows/ci.yml
- Overlays/Posix/Overlays/GCC/cmake/build_options.cmake
- README.md
This drops `clang` **9** and adds `gcc` **11** and `clang` **11** and **12**. Resolves #408.
> Update linux compilers and fix OOM issues

- .github/workflows/ci.yml
Only re-enabling for linux right now. Still disabled for android.
> Re-enable linux sccache

- Libraries/WNScripting/inc/WNEngine.inl
- Libraries/WNScripting/inc/WNFactory.h
- Libraries/WNScripting/inc/WNScriptHelpers.h
- Libraries/WNScripting/inc/WNScriptTLS.h
- Libraries/WNScripting/src/WNFactory.cpp
- engine/engine/src/script_export.cpp
- engine/support/src/log.cpp
- engine/support/src/string.cpp
- engine/support/src/subprocess.cpp
- engine/ui/src/ui_scripting_event_instancer.cpp
We were failing to retain the TLS data if we happened to hop
fibers during a call, this meant that if we created a window
and woke up on a new thread, we would have null tls data
meaning we could not make a call properly.
> Fix for scripting engine.

- Runtime/WNApplicationEntry/src/WNApplicationEntry.cpp
- externals/librocket/Source/Core/TTFFont/FontFaceHandle.cpp
This could create a terrible loop of loading fonts forever (or at least until a stack overflow). If we have the UI debugger around then logging will try to write UI log, whihc may load a font, which may log with may try to load a font etc etc.
> Small fix to logging.

- Libraries/WNScripting/inc/WNScriptTLS.h
- Libraries/WNScripting/inc/ast_node_types.h
- Libraries/WNScripting/src/WNCTranslator.cpp
- Libraries/WNScripting/src/WNJITEngine.cpp
- Libraries/WNScripting/src/add_builtins.cpp
- Libraries/WNScripting/src/convert_expression_to_ast.cpp
- Libraries/WNScripting/src/convert_function_to_ast.cpp
- Libraries/WNScripting/src/convert_parse_to_ast.cpp
- applications/editor/assets/ui/main.rml
- applications/editor/assets/ui/window.rml
- applications/script_test_runner/src/WNScriptTestRunner.cpp
- engine/engine_base/inc/context.h
- engine/engine_base/src/context.cpp
- engine/ui/inc/ui_scripting_event_instancer.h
- engine/ui/src/ui_scripting_event_instancer.cpp
This simply creates an extra function that primes the actor call.
So instead of having to inject a bunch of actor related business at the call-site, we can now just call the wrapper function that actually handles allocating the actor data, and it acts like a "normal" function call.
Furthermore this sets us up for 2 things
1) being able to defer an actor update until a future time
(# of frames)
2) Calling actions from C++. This will be important very soon
as the UI model is firming up.
> Another update to simplify actors.

- .build-ignore
- .github/labeler.yml
- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
- .github/workflows/push.yml
- .github/workflows/sync-labels.yml
- .github/workflows/update-license.yml
This will allow us to have stuff that is specific to PR's and specific to merging into `master`. I also added PR labeling as an example of divergent execution steps (can add more rules as we desire, help with searching for PR's). Eventually want to pull the analyze changes stuff out into only the PR stuff since for integration we always want to run everything but PR's we want to run only stuff related to changes. If we ever do releases as well those would only be needed in the push to `master` or with tags. Will need tp update PR required checks for branch protection after this is good to go. I will probably also split out format checking and build into their own shared workflows. Will help with future maintenance since the files will be smaller.
> Adjust CI to use shared workflows

- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
Better to do variable substitution instead of using GitHub Actions pre-processor substitution when using `run`. Prevents security issues. Didn't do this on the windows runners since there's other issues I'll have to address separately.
> Fix GitHub Actions variable substitution issues

- .github/workflows/ci.yml
- externals/librocket/Include/Rocket/Core/Context.h
- externals/librocket/Include/Rocket/Core/FontProvider.h
Having the quotes around it fails for glob patterns. C source changes are just to test it in CI.
> Fix C/C++ format checking

- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
- .github/workflows/push.yml
- CMakeLists.txt
Cleans up hot sccache GCS set-up is handled. Doesn't do the set-up for dependabot PR's. Does read only for PR's and read/write for `master`. Resolves #595, resolves #425 and resolves #597.
> Clean up sccache usage
